ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_acceleration: false
    
    # L'EKF devient le chef de la TF odom->base_link
    publish_tf: true
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # --- SOURCE 1 : Odométrie Laser (RF2O) ---
    # On fait confiance au Lidar pour la vitesse linéaire (X, Y)
    odom0: /odom_rf2o
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false, # Vitesse X, Y
                   false, false, false, # On ignore la rotation du Lidar (moins précise que l'IMU)
                   false, false, false]
    odom0_differential: false

    # --- SOURCE 2 : IMU ---
    # On fait confiance à l'IMU pour la vitesse de rotation (Yaw rate)
    imu0: /imu
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,  # Vitesse Angulaire Z (Yaw)
                  true,  false, false] # Accel X (Aide au démarrage)
    imu0_differential: false